name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
          check-latest: true
      - name: Ensure Go Is Properly Installed
        run: go version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
  
      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: go get -v ./...

      # - name: Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/go-contanerized:latest

      - name: Build
        run: go build -o bin .

      - name: Test
        run: go test -v ./cmd/...
